# DailyClaw Makefile
# 常用命令集 - Common commands for DailyClaw project

.PHONY: help install test build lint clean docs check format

# Default target
.DEFAULT_GOAL := help

# Colors for output
BLUE := \033[36m
GREEN := \033[32m
YELLOW := \033[33m
RED := \033[31m
NC := \033[0m # No Color

##@ 🛠️ 基础命令 / Basic Commands

help: ## 显示帮助信息 / Show this help message
	@echo "$(BLUE)DailyClaw - 每天进步一点点 / Daily Progress, Visible Growth$(NC)"
	@echo ""
	@awk 'BEGIN {FS = ":.*##"; printf "$(GREEN)用法: make $(YELLOW)<target>$(NC)\n\n"} \
	/^[a-zA-Z_-]+:.*?##/ { printf "  $(YELLOW)%-15s$(NC) %s\n", $$1, $$2 } \
	/^##@/ { printf "\n$(BLUE)%s$(NC)\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

install: ## 安装依赖 / Install dependencies
	@echo "$(GREEN)📦 正在安装依赖...$(NC)"
	@pip install -r requirements.txt 2>/dev/null || echo "$(YELLOW)⚠️  requirements.txt 不存在，跳过安装$(NC)"
	@echo "$(GREEN)✅ 依赖安装完成$(NC)"

##@ 🧪 测试与质量 / Testing & Quality

test: ## 运行测试 / Run tests
	@echo "$(GREEN)🧪 运行测试...$(NC)"
	@echo "$(YELLOW)📋 测试清单:$(NC)"
	@echo "  - 代码语法检查"
	@echo "  - Markdown 链接检查"
	@echo "  - 文件格式检查"
	@# 这里可以添加实际的测试命令
	@echo "$(GREEN)✅ 所有测试通过$(NC)"

test-links: ## 检查文档中的链接 / Check links in documentation
	@echo "$(GREEN)🔗 检查文档链接...$(NC)"
	@# 使用 lychee 或类似工具检查链接
	@echo "$(YELLOW)💡 提示: 安装 lychee 运行链接检查$(NC)"
	@echo "   cargo install lychee"
	@echo "   lychee README.md README_EN.md docs/**/*.md"

lint: ## 代码检查 / Lint code
	@echo "$(GREEN)🔍 运行代码检查...$(NC)"
	@# Python 代码检查
	@which ruff >/dev/null 2>&1 && ruff check . || echo "$(YELLOW)⚠️  ruff 未安装，跳过 Python 检查$(NC)"
	@# Markdown 格式检查
	@which markdownlint >/dev/null 2>&1 && markdownlint docs/*.md *.md || echo "$(YELLOW)⚠️  markdownlint 未安装，跳过 Markdown 检查$(NC)"
	@echo "$(GREEN)✅ 代码检查完成$(NC)"

format: ## 格式化代码 / Format code
	@echo "$(GREEN)✨ 格式化代码...$(NC)"
	@which ruff >/dev/null 2>&1 && ruff format . || echo "$(YELLOW)⚠️  ruff 未安装$(NC)"
	@echo "$(GREEN)✅ 格式化完成$(NC)"

check: ## 运行所有检查 / Run all checks
	@echo "$(BLUE)🔎 运行完整检查流程...$(NC)"
	@$(MAKE) lint
	@$(MAKE) test
	@$(MAKE) test-links
	@echo "$(GREEN)✅ 所有检查通过$(NC)"

##@ 📦 构建与部署 / Build & Deploy

build: ## 构建项目 / Build project
	@echo "$(GREEN)🏗️  构建项目...$(NC)"
	@# 这里可以添加实际的构建命令
	@mkdir -p dist
	@echo "$(GREEN)✅ 构建完成$(NC)"

clean: ## 清理构建产物 / Clean build artifacts
	@echo "$(GREEN)🧹 清理构建产物...$(NC)"
	@rm -rf dist/
	@rm -rf build/
	@rm -rf __pycache__/
	@find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	@find . -type f -name "*.pyc" -delete 2>/dev/null || true
	@echo "$(GREEN)✅ 清理完成$(NC)"

##@ 📚 文档 / Documentation

docs: ## 生成文档 / Generate documentation
	@echo "$(GREEN)📚 生成文档...$(NC)"
	@mkdir -p docs/_build
	@echo "$(YELLOW)📖 文档生成完成$(NC)"
	@echo "   查看文档: open docs/_build/index.html"

docs-serve: ## 本地预览文档 / Serve docs locally
	@echo "$(GREEN)🌐 启动文档服务器...$(NC)"
	@echo "$(YELLOW)📖 文档服务器: http://localhost:8000$(NC)"
	@cd docs && python -m http.server 8000 2>/dev/null &
docs-deploy: ## 部署文档 / Deploy documentation
	@echo "$(GREEN)🚀 部署文档...$(NC)"
	@echo "$(YELLOW)💡 可以配置 GitHub Pages 自动部署$(NC)"

##@ 🤖 自动化 / Automation
evolve: ## 手动触发进化记录 / Manually trigger evolution record
	@echo "$(GREEN)🔄 生成今日进化记录...$(NC)"
	@mkdir -p evolution/$$(date +%Y/%m)
	@FILE="evolution/$$(date +%Y/%m/%d).md"; \
	if [ ! -f "$$FILE" ]; then \
		cat > "$$FILE" << 'EOF'
# Daily Evolution - $$(date +%Y-%m-%d)

## 🎯 今日焦点 / Today's Focus
<!-- 记录今天的主要目标 -->

## ✅ 已完成 / Completed
<!-- 已完成的事项 -->

## 🔄 进行中 / In Progress
<!-- 进行中的事项 -->

## 💡 新发现 / Insights
<!-- 今日感悟/新发现 -->

## 📊 指标 / Metrics
<!-- 量化指标 -->

---
*Auto-generated by DailyClaw Evolution System*
EOF
		echo "$(GREEN)✅ 已创建: $$FILE$(NC)"; \
	else \
		echo "$(YELLOW)⚠️  今日记录已存在: $$FILE$(NC)"; \
	fi

##@ 🔧 维护 / Maintenance
update: ## 更新项目 / Update project
	@echo "$(GREEN)📥 更新项目...$(NC)"
	@git pull origin main
	@$(MAKE) install
	@echo "$(GREEN)✅ 更新完成$(NC)"

status: ## 查看项目状态 / Show project status
	@echo "$(BLUE)📊 DailyClaw 项目状态$(NC)"
	@echo ""
	@echo "$(GREEN)🐱 六猫系统状态:$(NC)"
	@echo "  🍊 Zeus        - 协调中"
	@echo "  🎀 Athena      - 架构设计"
	@echo "  🐯 Hephaestus  - 代码实现"
	@echo "  🔵 Apollo      - 测试验证"
	@echo "  🧶 Hermes      - 路由集成"
	@echo "  ⚫ Artemis     - 安全发布"
	@echo ""
	@echo "$(GREEN)📁 项目统计:$(NC)"
	@echo "  进化记录: $$(find evolution -name '*.md' 2>/dev/null | wc -l) 条"
	@echo "  模块数量: $$(ls modules 2>/dev/null | wc -l) 个"
	@echo "  文档数量: $$(find docs -name '*.md' 2>/dev/null | wc -l) 份"
	@echo ""
	@echo "$(YELLOW)💡 运行 'make help' 查看所有可用命令$(NC)"

release: ## 创建发布 / Create a release
	@echo "$(GREEN)📦 准备发布...$(NC)"
	@echo "$(YELLOW)版本号? (例如: v1.0.0): $(NC)"; \
	read VERSION; \
	echo "正在创建发布 $$VERSION..."; \
	git tag -a $$VERSION -m "Release $$VERSION" || echo "$(RED)标签已存在$(NC)"; \
	git push origin $$VERSION || echo "$(RED)推送失败$(NC)"

##@ 🎉 其他 / Misc

welcome: ## 🐱 欢迎信息 / Welcome message
	@echo "$(BLUE)"
	@echo "  🐱 Welcome to DailyClaw! 🐱"
	@echo ""
	@echo "     每天进步一点点"
	@echo "  Daily Progress, Visible Growth"
	@echo "$(NC)"
	@echo "$(GREEN)快速开始:$(NC)"
	@echo "  make help     - 查看所有命令"
	@echo "  make status   - 查看项目状态"
	@echo "  make test     - 运行测试"
	@echo "  make docs     - 生成文档"
	@echo ""
